name: Deploy Odoo to VM

# Script ini akan berjalan setiap kali ada 'push' ke branch 'main' atau 'Perubahan'
on:
  push:
    branches:
      - main
      - Perubahan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Masuk ke Server dan Update Aplikasi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        # Berikut adalah perintah yang akan dijalankan otomatis di terminal VM kamu
        script: |
          cd ~/Glass
          git fetch origin
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          docker build -t glass .
          docker rm -f aplikasi-glass
          docker run -d \
            -p 80:8069 \
            -e PORT=8069 \
            -e PGHOST=server-db \
            -e PGPORT=5432 \
            -e PGUSER=odoo \
            -e PGPASSWORD=odoo \
            --name aplikasi-glass \
            --network jaringan-odoo \
            glass